### ISSUE TITLE
ANSI APIs definitions prevent Unicode users / groups from being used

### ISSUE THREAD

**Issue by Iristyle** [djberg96/win32-security#8]
ANIS APIs `ConvertSidToStringSidA`, `ConvertStringSidToSidA`, `LookupAccountNameA`, `LookupAccountSidA`, `ConvertSecurityDescriptorToStringSecurityDescriptorA` and `ConvertStringSecurityDescriptorToSecurityDescriptorA` are used in https://github.com/djberg96/win32-security/blob/ffi/lib/win32/security/windows/functions.rb

For instance, this causes problems when trying to work with the Administrators group in German Windows, since that account name contains an umlaut.  The wide string versions of these APIs should be used to properly support international versions of Windows.

**Comment by djberg96** [comment]
This shouldn't be too difficult to update.

**Comment by djberg96** [comment]
@Iristyle I've started a wide_char branch. Looking at this some more I'm not sure anything other than the LookupAccount functions need to be changed. Two of the functions aren't even used (I'll remove them), and the SID conversion functions don't seem like they really need wide versions.

At the moment I still have one test failure I need to work out.

**Comment by djberg96** [comment]
@Iristyle Please checkout the wide_char branch and let me know how that works for you.

**Comment by djberg96** [comment]
@phasis68 Can you please confirm that the wide_char branch works for you?

**Comment by phasis68** [comment]
The wide_char branch works for me.

**Comment by djberg96** [comment]
@Iristyle I released 0.4.0 this morning. Thanks for the report.
