### ISSUE TITLE
Creating new SID without argument fails (read_string used on non-zero-terminated data)

### ISSUE THREAD

**Issue by nmeilick** [djberg96/win32-security#9]
Hi,

thanks very much for the nice library. I've noticed the following issue in v0.3.2.
When calling Win32::Security::SID.new without any arguments and thus using the user account associated with the calling thread, the SID is not read properly:

```
@sid = token_info.read_string
```

This stops at the first zero. To fix it:

```
  length = GetLengthSid(token_info)  
  @sid = token_info.read_string(length)
```

Best regards,
Norman

**Comment by djberg96** [comment]
Fixed and released in 0.3.3. Thanks for the report.
